RECIPES = [
    {
        "id": 1,
        "name": "Pizza",
        "ingredients": "Cheese, Dough, Tomato Sauce",
        "time": "35 min",
        "difficulty": "Medium",
        "category": "Dinner",
        "servings": 4,
        "description": "A bubbly cheese pizza with a quick tomato base for weeknight cravings.",
    },
    {
        "id": 2,
        "name": "Burger",
        "ingredients": "Bun, Patty, Cheese",
        "time": "25 min",
        "difficulty": "Easy",
        "category": "Lunch",
        "servings": 2,
        "description": "A simple cheeseburger with a toasted bun and classic toppings.",
    },
    {
        "id": 3,
        "name": "Veggie Pasta",
        "ingredients": "Pasta, Bell Pepper, Tomato, Garlic, Olive Oil",
        "time": "30 min",
        "difficulty": "Easy",
        "category": "Dinner",
        "servings": 3,
        "description": "Colorful vegetable pasta tossed in garlic and olive oil.",
    },
    {
        "id": 4,
        "name": "Chicken Curry",
        "ingredients": "Chicken, Onion, Tomato, Ginger, Garlic, Spices",
        "time": "45 min",
        "difficulty": "Medium",
        "category": "Dinner",
        "servings": 4,
        "description": "A warming chicken curry built with tomatoes, aromatics, and spices.",
    },
    {
        "id": 5,
        "name": "Fruit Salad",
        "ingredients": "Apple, Banana, Grapes, Orange, Honey",
        "time": "10 min",
        "difficulty": "Easy",
        "category": "Snack",
        "servings": 2,
        "description": "A bright fruit bowl finished with a light honey drizzle.",
    },
    {
        "id": 6,
        "name": "Pancakes",
        "ingredients": "Flour, Milk, Egg, Sugar, Baking Powder",
        "time": "20 min",
        "difficulty": "Easy",
        "category": "Breakfast",
        "servings": 3,
        "description": "Fluffy breakfast pancakes that cook quickly on a griddle.",
    },
]
