RECIPES = [
    {
        "id": 1,
        "name": "Pizza",
        "ingredients": "Cheese, Dough, Tomato Sauce",
        "time": "35 min",
        "difficulty": "Medium",
        "category": "Dinner",
    },
    {
        "id": 2,
        "name": "Burger",
        "ingredients": "Bun, Patty, Cheese",
        "time": "25 min",
        "difficulty": "Easy",
        "category": "Lunch",
    },
    {
        "id": 3,
        "name": "Veggie Pasta",
        "ingredients": "Pasta, Bell Pepper, Tomato, Garlic, Olive Oil",
        "time": "30 min",
        "difficulty": "Easy",
        "category": "Dinner",
    },
    {
        "id": 4,
        "name": "Chicken Curry",
        "ingredients": "Chicken, Onion, Tomato, Ginger, Garlic, Spices",
        "time": "45 min",
        "difficulty": "Medium",
        "category": "Dinner",
    },
    {
        "id": 5,
        "name": "Fruit Salad",
        "ingredients": "Apple, Banana, Grapes, Orange, Honey",
        "time": "10 min",
        "difficulty": "Easy",
        "category": "Snack",
    },
    {
        "id": 6,
        "name": "Pancakes",
        "ingredients": "Flour, Milk, Egg, Sugar, Baking Powder",
        "time": "20 min",
        "difficulty": "Easy",
        "category": "Breakfast",
    },
]
